Route for logging into IDE extensions using custom URL scheme
Testaustime/testaustime-frontend pull request #464
Opened 2024-01-03 21:03 UTC by ahnl

In case user is logged out it redirects the user to log in and back to the authorize route.

<img width="897" alt="Screenshot 2024-01-03 at 22 47 01" src="https://github.com/Testaustime/testaustime-frontend/assets/46541386/deb771bb-90d5-4530-a694-84bcdbbc8168">

See also: PR for testaustime-vscode
https://github.com/Testaustime/testaustime-vscode/pull/11

2024-02-10 16:02 UTC, Eldemarkki requested changes
Looks good! I requested a few changes but otherwise this is good. 

I think we should merge https://github.com/Testaustime/testaustime-vscode/pull/11 before this, so that this functionality won't appear "broken" in the meanwhile.

2024-02-10 16:02 UTC, Eldemarkki commented on src/app/[locale]/authorize/page.tsx
> +      <a href={`vscode://testausserveri-ry.testaustime/authorize?${token}`}>
The query string isn't valid, it needs to be a key-value pair. This will need a change in https://github.com/Testaustime/testaustime-vscode/pull/11 too.
```suggestion
      <a href={`vscode://testausserveri-ry.testaustime/authorize?token=${token}`}>
```

2024-02-10 16:02 UTC, Eldemarkki commented on src/app/[locale]/authorize/page.tsx
> +        <Button>{t("authorize.continue", { username })}</Button>
Having a `<button>` inside of an `<a>` is not valid according to HTML5 specification, we should change this to something else. Here's an example of how to do it with Mantine: https://mantine.dev/guides/polymorphic/#what-is-a-polymorphic-component

```jsx
<Button component="a" href="https://mantine.dev/" target="_blank">
  Mantine website
</Button>
```

2024-02-10 16:02 UTC, Eldemarkki commented on src/app/[locale]/authorize/page.tsx
> +        <Link href="profile">{t("authorize.notWorking.link")}</Link>
Probably doesn't affect the functionality but I think this should be `/profile`. Though if it changes the functionality then it's ok as is.
```suggestion
        <Link href="/profile">{t("authorize.notWorking.link")}</Link>
```

2024-02-13 23:15 UTC, ahnl commented on src/app/[locale]/authorize/page.tsx
> +        <Link href="profile">{t("authorize.notWorking.link")}</Link>
If this would have a slash in front of it, it would point to /profile instead of /[locale]/profile.

2024-02-13 23:25 UTC, ahnl commented on src/app/[locale]/authorize/page.tsx
> +      <a href={`vscode://testausserveri-ry.testaustime/authorize?${token}`}>
Corresponding change made in testaustime-vscode. https://github.com/Testaustime/testaustime-vscode/pull/11/commits/22c06151ce0f8bf34b5105d841c410447fc23cb2

2024-02-13 23:28 UTC, ahnl commented
The requested changes have now been made.

Regarding the order of which repository to merge first, I think this should come first. The function does not show up in the web version unless you manually decide to go to the /authorize?editor=vscode path. Whereas if the editor came first, then the well featured function would not work at all.

2024-02-17 15:36 UTC, Eldemarkki approved these changes

2024-02-17 15:36 UTC, merged

2024-02-17 15:36 UTC, Eldemarkki commented
Thanks for your contribution!